version: '3'
services:
  backend:
    image: nemal2/hotel-backend:latest
    ports:
      - "8080:8080"
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - app-network
  
  frontend:
    image: nemal2/hotel-frontend:latest
    ports:
      - "80:3000"
    depends_on:
      - backend
    restart: always
    environment:
      # Use the service name instead of IP
      - REACT_APP_API_URL=http://backend:8080
    networks:
      - app-network

networks:
  app-network:
    driver: bridge