
version: '3.8'
services:
  backend:
    image: nemal2/hotel-backend:latest
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb+srv://nemalperera3:Zza13ZD6CCYJ7N9h@hotelspring2.5ly0c.mongodb.net/HotelSpring

  frontend:
    image: nemal2/hotel-frontend:latest
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
